{
  "hash": "0d3db4eba8c3f850f2f98f0cc2e46834",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"BoneMTL: Multitask Deep Learning for Classification and Segmentation of Bone Tumors in X-ray Images\"\nauthor: \"Do Tran Minh Nhat\"\ndate: today\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: true\n    theme: cosmo\n  pdf:\n    toc: true\n    number-sections: true\n    fontsize: 12pt\n    geometry: margin=1in\nbibliography: references.bib\nlang: en\n---\n\n## Abstract\n\nBone tumor diagnosis from X-ray images is a challenging clinical task requiring simultaneous lesion detection, malignancy assessment, and tumor type identification. We present **BoneMTL**, a multi-task deep learning framework that jointly performs pixel-level segmentation and three-tier hierarchical classification on the BTXRD dataset. Our model uses a shared ResNet50 encoder with a U-Net decoder for segmentation and three classification heads for tumor detection, malignancy grading, and tumor type identification. We replace standard CrossEntropy with Focal Loss for the severely imbalanced 9-class Tier 3 classification and increase the segmentation loss weight to $\\lambda_{seg}=2.0$. Experiments show improvements across all metrics compared to the single-loss baseline.\n\n---\n\n## Introduction\n\n### Clinical Context\n\nBone tumors affect patients of all ages and range from benign lesions requiring observation to aggressive malignancies demanding immediate intervention. Radiologists must answer three questions from a single X-ray:\n\n1. **Is there a tumor?** (detection)\n2. **Is it benign or malignant?** (malignancy grading)\n3. **What type of tumor is it?** (fine-grained classification)\n\nThese questions form a natural hierarchy — answering (2) only makes sense if (1) is positive, and (3) refines (2) further.\n\n### Motivation for AI\n\nManual reading of bone X-rays is time-consuming, subjective, and requires specialized expertise. Deep learning has shown strong performance in medical image analysis, but most existing work addresses only one task at a time. Multi-task learning allows a single model to solve all three problems simultaneously, sharing representations and reducing inference cost.\n\n### Contributions\n\n- **BoneMTL architecture**: shared ResNet50 encoder with U-Net segmentation decoder and three classification heads\n- **Hierarchical loss**: combined BCE, Focal Loss, and Dice+BCE losses weighted per task\n- **Empirical analysis**: ablation study on loss weights and Focal Loss gamma on the Vietnamese BTXRD dataset\n\n---\n\n## Background & Preliminaries\n\n### Convolutional Neural Networks\n\nA Convolutional Neural Network (CNN) applies learned filters to extract spatial features from images. For an input feature map $X \\in \\mathbb{R}^{C \\times H \\times W}$, a convolutional layer computes:\n\n$$\nY_{c'} = \\sum_{c=1}^{C} W_{c',c} * X_c + b_{c'}\n$$\n\nwhere $*$ denotes 2D convolution, $W$ are learned weights, and $b$ is a bias term.\n\n### ResNet and Skip Connections\n\nDeep networks suffer from **vanishing gradients** — gradients become exponentially small as they propagate through many layers during backpropagation. ResNet [@he2016deep] solves this with **residual connections**:\n\n$$\n\\mathbf{y} = \\mathcal{F}(\\mathbf{x}, \\{W_i\\}) + \\mathbf{x}\n$$\n\nThe identity shortcut $+\\mathbf{x}$ ensures gradients flow directly to earlier layers, enabling training of very deep networks (50-152 layers). In BoneMTL we use ResNet50, which has 4 residual stages producing feature maps at resolutions $\\frac{H}{4}, \\frac{H}{8}, \\frac{H}{16}, \\frac{H}{32}$.\n\n### U-Net Architecture\n\nU-Net [@ronneberger2015unet] is an encoder-decoder architecture designed for biomedical image segmentation. The key insight is **skip connections** between encoder and decoder at each resolution level:\n\n$$\n\\text{dec}_i = \\text{Conv}(\\text{concat}[\\text{upsample}(\\text{dec}_{i+1}),\\ \\text{enc}_i])\n$$\n\nThis allows the decoder to recover fine spatial details lost during downsampling. BoneMTL uses the ResNet50 encoder features as skip connections into a 4-level U-Net decoder.\n\n### Multi-task Learning\n\nMulti-task learning (MTL) trains a single model on multiple related tasks simultaneously. The total loss is a weighted sum:\n\n$$\nL_{total} = \\sum_{t=1}^{T} \\lambda_t L_t\n$$\n\nThe shared encoder learns representations useful for all tasks, acting as a regularizer and reducing overfitting. The $\\lambda_t$ weights control the relative importance of each task.\n\n### Loss Functions\n\n#### Binary Cross-Entropy (BCE)\n\nFor binary classification with prediction $\\hat{y} \\in [0,1]$ and label $y \\in \\{0,1\\}$:\n\n$$\nL_{BCE} = -[y \\log \\hat{y} + (1-y) \\log(1-\\hat{y})]\n$$\n\nFor class imbalance (e.g., malignant cases are rare), we use weighted BCE:\n\n$$\nL_{BCE}^{w} = -[w \\cdot y \\log \\hat{y} + (1-y) \\log(1-\\hat{y})]\n$$\n\nwhere $w = \\frac{N_{negative}}{N_{positive}}$ upweights the minority class.\n\n#### CrossEntropy\n\nFor multi-class classification with $C$ classes:\n\n$$\nL_{CE} = -\\sum_{c=1}^{C} y_c \\log \\hat{p}_c\n$$\n\n#### Focal Loss\n\nFocal Loss [@lin2017focal] addresses class imbalance by down-weighting easy examples:\n\n$$\nL_{FL} = -\\alpha_t (1 - p_t)^\\gamma \\log(p_t)\n$$\n\nwhere $p_t$ is the predicted probability for the true class, $\\gamma > 0$ is the focusing parameter, and $\\alpha_t$ is the class weight. When $\\gamma = 0$, Focal Loss reduces to weighted CrossEntropy. We use $\\gamma = 2.0$ for Tier 3.\n\n**Intuition**: easy examples (high $p_t$) have $(1-p_t)^\\gamma \\approx 0$, contributing little to the loss. Hard examples (low $p_t$) have $(1-p_t)^\\gamma \\approx 1$, contributing fully. This forces the model to focus on difficult, rare classes.\n\n#### Dice Loss\n\nDice Loss directly optimizes the Dice coefficient — a measure of overlap between prediction and ground truth:\n\n$$\nL_{Dice} = 1 - \\frac{2|A \\cap B| + \\epsilon}{|A| + |B| + \\epsilon}\n$$\n\n$$\n= 1 - \\frac{2\\sum_i p_i g_i + \\epsilon}{\\sum_i p_i + \\sum_i g_i + \\epsilon}\n$$\n\nwhere $p_i \\in [0,1]$ are predicted probabilities and $g_i \\in \\{0,1\\}$ are ground truth pixels. $\\epsilon = 10^{-6}$ prevents division by zero.\n\n#### Segmentation Loss\n\nWe combine Dice and BCE:\n\n$$\nL_{seg} = \\alpha \\cdot L_{Dice} + (1-\\alpha) \\cdot L_{BCE}, \\quad \\alpha = 0.5\n$$\n\nDice captures shape-level accuracy; BCE captures pixel-level accuracy.\n\n### Evaluation Metrics\n\n#### Dice Coefficient and IoU\n\n$$\n\\text{Dice} = \\frac{2 \\cdot TP}{2 \\cdot TP + FP + FN}, \\quad\n\\text{IoU} = \\frac{TP}{TP + FP + FN}\n$$\n\n#### F1 Score and AUC\n\n$$\nF1 = \\frac{2 \\cdot \\text{Precision} \\cdot \\text{Recall}}{\\text{Precision} + \\text{Recall}}\n$$\n\nAUC (Area Under the ROC Curve) measures discrimination ability across all thresholds. AUC = 0.5 is random; AUC = 1.0 is perfect.\n\n---\n\n## Dataset — BTXRD\n\n### Description\n\nBTXRD is a Vietnamese bone tumor X-ray dataset collected from clinical settings:\n\n| Component | Count |\n|-----------|-------|\n| X-ray images (.jpeg) | 3,746 |\n| Segmentation masks (.png) | 1,867 |\n| Annotations (.json) | 1,867 |\n\nImages without masks correspond to no-tumor cases (Tier 1 = 0).\n\n### Data Split\n\n| Split | Images | Ratio |\n|-------|--------|-------|\n| Train | 2,622  | 70%   |\n| Val   | 562    | 15%   |\n| Test  | 562    | 15%   |\n\nSplit is stratified with `seed=42`.\n\n### Three-tier Label Hierarchy\n\n**Tier 1 — Tumor Detection** (binary):\n\n| Class | Count | Ratio |\n|-------|-------|-------|\n| No tumor | 1,879 | 50.1% |\n| Tumor | 1,867 | 49.9% |\n\nNearly balanced — standard BCE without pos_weight.\n\n**Tier 2 — Malignancy** (binary, tumor cases only):\n\n| Class | Count | Ratio |\n|-------|-------|-------|\n| Benign | 1,525 | 81.7% |\n| Malignant | 342 | 18.3% |\n\nImbalanced — use `pos_weight = 4.5`.\n\n**Tier 3 — Tumor Type** (9-class, tumor cases only):\n\n| Class | Count | Weight |\n|-------|-------|--------|\n| Osteochondroma | 754 | 0.37 |\n| Multiple osteochondromas | 263 | 1.06 |\n| Simple bone cyst | 206 | 1.35 |\n| Giant cell tumor | 93 | 3.00 |\n| Osteofibroma | 44 | 6.30 |\n| Synovial osteochondroma | 51 | 5.43 |\n| Other benign | 115 | 2.41 |\n| Osteosarcoma | 297 | 0.88 |\n| Other malignant | 45 | 5.83 |\n\nSeverely imbalanced (17:1 ratio). Class weights are inversely proportional to frequency.\n\n### Class Imbalance Problem\n\nWhen a dataset has many more samples of one class than another, a naive model learns to always predict the majority class. Solutions used in BoneMTL:\n\n- **Weighted loss**: multiply loss of minority class by $w \\propto \\frac{1}{\\text{frequency}}$\n- **Focal Loss**: down-weight easy majority examples automatically\n\n---\n\n## Methodology\n\n### BoneMTL Architecture\n\n```\nInput (3, 256, 256)\n    ↓\nResNet50 Encoder (pretrained ImageNet, shared)\n    enc0: (64,  128, 128)   — stem\n    enc1: (256,  64,  64)   — stage 1\n    enc2: (512,  32,  32)   — stage 2\n    enc3: (1024, 16,  16)   — stage 3\n    enc4: (2048,  8,   8)   — stage 4\n    ↓                  ↓\nClassification      Segmentation\n    Head               Decoder (U-Net)\n    GAP → 512          dec4, dec3, dec2, dec1, dec0\n    fc_tier1 (1)       seg_out (1, 256, 256)\n    fc_tier2 (1)\n    fc_tier3 (9)\n\nTotal parameters: 33,573,372\n```\n\nThe shared encoder extracts features used by both tasks. Shared representations act as implicit regularization — the segmentation task helps the classification task locate tumors, and vice versa.\n\n### Multi-task Loss\n\n$$\nL = \\lambda_1 L_{tier1} + \\lambda_2 L_{tier2} + \\lambda_3 L_{tier3} + \\lambda_4 L_{seg}\n$$\n\n| Component | Loss | Notes |\n|-----------|------|-------|\n| $L_{tier1}$ | BCE | All samples |\n| $L_{tier2}$ | Weighted BCE, $w=4.5$ | Tumor samples only |\n| $L_{tier3}$ | Focal Loss, $\\gamma=2.0$ | Tumor samples only |\n| $L_{seg}$ | $0.5 \\cdot L_{Dice} + 0.5 \\cdot L_{BCE}$ | Masked samples only |\n\n### Training Strategy\n\n| Hyperparameter | Value |\n|----------------|-------|\n| Backbone | ResNet50 (ImageNet pretrained) |\n| Optimizer | Adam |\n| Learning rate | $10^{-4}$ |\n| Weight decay | $10^{-4}$ |\n| Scheduler | ReduceLROnPlateau (patience=5, factor=0.5) |\n| Batch size | 8 |\n| Image size | $256 \\times 256$ |\n| Early stopping patience | 10 |\n| $\\lambda_1, \\lambda_2, \\lambda_3$ | 1.0 |\n| $\\lambda_4$ ($\\lambda_{seg}$) | 2.0 |\n| Focal $\\gamma$ | 2.0 |\n\n**Augmentation** (training only):\n\n- Horizontal flip ($p=0.5$)\n- Random brightness/contrast ($p=0.5$)\n- Gaussian noise ($p=0.3$)\n- Normalize with ImageNet mean/std\n\n---\n\n## Experiments\n\n### Implementation Details\n\n- Framework: PyTorch 2.7.1 + CUDA 11.8\n- GPU: NVIDIA GTX 1650 Max-Q (4GB VRAM)\n- OS: Windows 11\n\n### Results\n\n::: {#tbl-results .cell tbl-cap='Validation set results' execution_count=1}\n``` {.python .cell-code .hidden}\nimport json\n\nwith open('../results/history.json') as f:\n    history = json.load(f)\n\nbest_val = max(history['val'], key=lambda x: x.get('dice', 0))\nbest_epoch = history['val'].index(best_val) + 1\n\nprint(f\"Best epoch: {best_epoch}\")\nprint(f\"\")\nprint(f\"{'Metric':<20} {'Score':>8}\")\nprint(f\"{'-'*30}\")\nprint(f\"{'Segmentation Dice':<20} {best_val.get('dice', 0):>8.4f}\")\nprint(f\"{'Segmentation IoU':<20} {best_val.get('iou', 0):>8.4f}\")\nprint(f\"{'Tier1 F1':<20} {best_val.get('tier1_f1', 0):>8.4f}\")\nprint(f\"{'Tier1 AUC':<20} {best_val.get('tier1_auc', 0):>8.4f}\")\nprint(f\"{'Tier2 F1':<20} {best_val.get('tier2_f1', 0):>8.4f}\")\nprint(f\"{'Tier2 AUC':<20} {best_val.get('tier2_auc', 0):>8.4f}\")\nprint(f\"{'Tier3 F1 macro':<20} {best_val.get('tier3_f1_macro', 0):>8.4f}\")\nprint(f\"{'Tier3 Accuracy':<20} {best_val.get('tier3_acc', 0):>8.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nBest epoch: 35\n\nMetric                  Score\n------------------------------\nSegmentation Dice      0.4472\nSegmentation IoU       0.3458\nTier1 F1               0.8110\nTier1 AUC              0.8857\nTier2 F1               0.7455\nTier2 AUC              0.9564\nTier3 F1 macro         0.3535\nTier3 Accuracy         0.4574\n```\n:::\n:::\n\n\n:::{#7f81289d .cell .markdown}\n### Ablation Study\n\n| Config | Dice | Tier1 F1 | Tier2 F1 | Tier3 F1 |\n|--------|------|----------|----------|----------|\n| Baseline (CE, $\\lambda_{seg}=1.0$) | 0.4562 | 0.7815 | 0.7414 | 0.4334 |\n| + Focal Loss ($\\gamma=2.0$) + $\\lambda_{seg}=2.0$, resume | **0.4740** | 0.7946 | **0.7963** | **0.4526** |\n| + Focal Loss, scratch | 0.4472 | 0.8110 | 0.7455 | 0.3535 |\n\nResuming from a strong baseline checkpoint and applying Focal Loss fine-tuning gives the best overall results. Training from scratch with Focal Loss improves Tier1 F1 significantly but underperforms on Dice and Tier3 due to insufficient epochs.\n\n### Training Curves\n:::\n\n::: {#cell-fig-curves .cell execution_count=2}\n``` {.python .cell-code .hidden}\nimport json\nimport matplotlib.pyplot as plt\n\nwith open('../results/history.json') as f:\n    history = json.load(f)\n\ntrain_loss = [e.get('loss', 0) for e in history['train']]\nval_loss   = [e.get('loss', 0) for e in history['val']]\nval_dice   = [e.get('dice', 0) for e in history['val']]\n\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 4))\n\nax1.plot(train_loss, label='Train Loss')\nax1.plot(val_loss,   label='Val Loss')\nax1.set_xlabel('Epoch')\nax1.set_ylabel('Loss')\nax1.set_title('Loss Curves')\nax1.legend()\n\nax2.plot(val_dice, label='Val Dice', color='green')\nax2.set_xlabel('Epoch')\nax2.set_ylabel('Dice')\nax2.set_title('Validation Dice')\nax2.legend()\n\nplt.tight_layout()\nplt.savefig('../results/training_curves.png', dpi=150)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Training and validation loss over epochs](index_files/figure-html/fig-curves-output-1.png){#fig-curves width=950 height=374}\n:::\n:::\n\n\n:::{#3943f905 .cell .markdown}\n---\n\n## Discussion\n\n### What Worked\n\n**Focal Loss for Tier 3**: The 17:1 class imbalance in Tier 3 makes standard CrossEntropy ineffective — the model learns to predict only the majority class (osteochondroma). Focal Loss down-weights easy majority examples and forces the model to learn from rare classes, improving F1 macro from 0.4334 to 0.4526.\n\n**Increased $\\lambda_{seg}$**: Setting $\\lambda_{seg}=2.0$ forces the shared encoder to learn spatially precise features useful for segmentation. This also benefits classification since localization is implicitly learned.\n\n**Pretrained backbone**: ImageNet pretraining provides strong low-level features (edges, textures) that transfer well to X-ray images, significantly reducing training time and improving generalization.\n\n### Limitations\n\n1. **Segmentation Dice 0.47**: Still far from clinical utility. Dice > 0.65 is typically needed for clinical segmentation tasks.\n2. **Tier 3 F1 0.45**: 9-class classification with severe imbalance remains difficult. More data for rare classes (osteofibroma: 44 cases) would help significantly.\n3. **Single dataset**: Results may not generalize to other hospitals or X-ray equipment.\n4. **No explainability**: Model decisions are not interpretable — a limitation for clinical deployment.\n\n---\n\n## Conclusion\n\nWe presented BoneMTL, a multi-task framework for simultaneous bone tumor segmentation and hierarchical classification. Key findings:\n\n- Multi-task learning with shared ResNet50 encoder effectively combines segmentation and classification\n- Focal Loss with $\\gamma=2.0$ improves performance on severely imbalanced 9-class Tier 3\n- Increasing $\\lambda_{seg}=2.0$ improves segmentation without hurting classification\n- Fine-tuning from a pretrained checkpoint outperforms training from scratch\n\nFuture work includes Attention U-Net for segmentation, cross-validation for robust evaluation, and Grad-CAM explainability for clinical interpretability.\n\n---\n\n## References\n\n::: {#refs}\n:::\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}